### ISSUE TITLE
Error when open the app

### ISSUE THREAD

**Issue by matsumurae** [murgatt/recode-converter#295]
**Describe the bug**
There's no way to use the app with the latest version. First time launch always throws "A Javascript error occurred in the main process".

**To Reproduce**
Open the app (2.0.8).

**Expected behavior**
Use the app as it should be.

**Screenshots**
<img width="328" alt="Captura de pantalla 2024-09-24 a las 11 48 30" src="https://github.com/user-attachments/assets/71c23f4e-88d4-411f-9900-ddc34a8b398d">

**Desktop:**
 - OS: Mac OS (Intel)
 - Version: Sonoma 14.6.1
 - App: Latest, 2.0.8

**Comment by murgatt** [comment]
Thank you for reporting the issue @matsumurae and sorry for the inconvenience. It looks like a specific issue with Intel Mac, I reproduced on two Intel but not on my M1. Note that the issue is slightly different on Sequoia 15.0.
Did you successfully use a previous version of Recode Converter before?

I'll look into it. As a workaround, you can use [2.0.3](https://github.com/murgatt/recode-converter/releases/download/v2.0.3/Recode-Converter-Mac-2.0.3-Installer.dmg). This version seems to be functional on both Intel and Silicon.
